export const env = {
  ROOT_DOMAIN: process.env.NEXT_PUBLIC_ROOT_DOMAIN!,
  UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL!,
  UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN!,
};
